# Generated by Django 5.0.7 on 2024-07-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_my_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
